logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/study/h2/data/test2
#    username: sa
#    password:
