logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
#  datasource:
##    url: jdbc:h2:tcp://localhost/~/study/h2/data/test2
#    url: jdbc:h2:tcp://localhost/E:\h2\spring-db
#    username: sa
#    password:
